Repository SeoulBomo/SeoulBomo.FE, pull requests merged in 2023-05, with the labels that each got.

#3 [Feat] 홈화면 layout setting, header 구현 및 bg-color 변경
  .vscode/settings.json
  package-lock.json
  package.json
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/header.tsx
Labels: 👨🏻‍💻작업중, 👥논의필요, 태강

#4 [Feat] CardFrame 및 모의 계산 카드 구현
  public/fonts/PretendardVariable.woff2
  src/components/main/CalculateCard.tsx
  src/components/main/CardFrame.tsx
  src/utils/font.ts
  tailwind.config.js
Labels: 👨🏻‍💻작업중, 👥논의필요, 👀리뷰, 가현

#6 feat: Pretendard Font 적용
  src/app/layout.tsx
Labels: ✅완료, 👀리뷰, 가현

#7 [Feat] Popular 카드 구현
  src/components/main/CardFrame.tsx
  src/components/main/PopularCard.tsx
  tailwind.config.js
Labels: 👨🏻‍💻작업중, 👀리뷰, 가현

#8 [Feat] 복지 소식 카드 구현
  src/app/page.tsx
  src/components/main/CardFrame.tsx
  src/components/main/NewsCard.tsx
  src/components/main/PopularCard.tsx
Labels: ✅완료, 👀리뷰, 가현

#10 [Feat] 헤더 구현 및 cardFrame style 변경
  public/images/BomoLogo.png
  src/app/page.tsx
  src/components/header.tsx
  src/components/main/CardFrame.tsx
Labels: ✅완료, 👀리뷰, 가현

#11 [Feat] 검색바 및 필터링 퍼블리싱
  public/images/child.png
  public/images/infant.png
  public/images/teen.png
  src/components/main/filterFrame.tsx
  src/components/main/filterSection.tsx
  src/components/main/radioBox.tsx
  src/components/main/searchFrame.tsx
Labels: 👨🏻‍💻작업중, 👀리뷰, 가현

#12 [Refactor] cardFrame 반응형 리팩토링, header 이동, CardFrame Page div style 추가
  src/app/layout.tsx
  src/app/page.tsx
  src/components/main/CalculateCard.tsx
  src/components/main/CardFrame.tsx
Labels: ✅완료, 👀리뷰, 태강

#13 [Feat] Information 페이지 구현
  src/components/information/InformationCard.tsx
  src/components/information/InformationFrame.tsx
Labels: ✅완료, 👀리뷰, 가현

#14 [Feat] 통합 검색 결과 화면 및 필터 검색 결과 화면 구현
  src/components/SearchCard.tsx
  src/components/filterSearch/FilterSearchFrame.tsx
  src/components/information/InformationCard.tsx
  src/components/information/InformationFrame.tsx
  src/components/mainSearch/MainSearchFrame.tsx
Labels: 👨🏻‍💻작업중, 👀리뷰, 가현

#15 [Feat] 지도 검색 결과 페이지 구현
  src/components/SearchCard.tsx
  src/components/mapSearch/MapSearchFrame.tsx
Labels: ✅완료, 👀리뷰, 가현

#18 [Feat] 마이페이지 구현
  src/components/my/MypageFrame.tsx
Labels: ✅완료, 👀리뷰, 가현

#19 [Feat] header, login, search 페이지 반응형 구현
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/search/page.tsx
  src/components/Logo.tsx
  src/components/SearchCard.tsx
  src/components/header.tsx
  src/components/login/LoginFrame.tsx
  src/components/main/FilterSection/FilterSection.tsx
  src/components/main/FilterSection/RadioBox.tsx
  src/components/main/map/MapFrame.tsx
  src/components/mainSearch/MainSearchFrame.tsx
Labels: ✅완료, 👀리뷰, 태강

#23 [Feat] 보육기반 페이지 구현
  public/images/careEstimate1.gif
  src/components/policyDetail/childCare/CareEstimate.tsx
  src/components/policyDetail/childCare/CareExtended.tsx
  src/components/policyDetail/childCare/CareProcess.tsx
  src/components/policyDetail/childCare/CareWaitingAdmission.tsx
Labels: ✅완료, 👀리뷰, 가현

#24 [Feature] information 페이지 반응형 구현
  src/app/information/(business)/benefit/page.tsx
  src/app/information/(business)/care/page.tsx
  src/app/information/(business)/infant-benefit/page.tsx
  src/app/information/(business)/layout.tsx
  src/app/information/(business)/pay/page.tsx
  src/app/information/(policy)/center/page.tsx
  src/app/information/(policy)/credit/page.tsx
  src/app/information/(policy)/expansion/page.tsx
  src/app/information/(policy)/history/page.tsx
  src/app/information/(policy)/layout.tsx
  src/app/information/(policy)/professional/page.tsx
  src/app/information/(policy)/reform/page.tsx
  src/app/information/(policy)/status/page.tsx
  src/app/information/page.tsx
  src/components/Header.tsx
  src/components/information/InformationCard.tsx
  src/components/information/InformationFrame.tsx
  src/components/policyDetail/business/BusiessBenefit.tsx
  src/components/policyDetail/business/BusinessCare.tsx
  src/components/policyDetail/business/BusinessInfantBenefit.tsx
  src/components/policyDetail/business/BusinessPay.tsx
  src/components/policyDetail/policy/PolicyCenter.tsx
  src/components/policyDetail/policy/PolicyCredit.tsx
  src/components/policyDetail/policy/PolicyExpansion.tsx
  src/components/policyDetail/policy/PolicyExpert.tsx
  src/components/policyDetail/policy/PolicyHistory.tsx
  src/components/policyDetail/policy/PolicyProfessional.tsx
  src/components/policyDetail/policy/PolicyReform.tsx
  src/components/policyDetail/policy/PolicyState.tsx
  src/components/policyDetail/policy/PolicyStatus.tsx
Labels: ✅완료, 👀리뷰, 태강

#26 [Feat] 카카오 맵 구현
  package.json
  src/app/detail/page.tsx
  src/components/detail/DetailFrame.tsx
  src/components/detail/KakaoMap.tsx
Labels: 👨🏻‍💻작업중, 👥논의필요, 👀리뷰, 가현

#27 [FIX] 크로스 브라우징 CSS 에러 해결
  src/app/about-us/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/map/page.tsx
  src/app/mypage/page.tsx
  src/app/page.tsx
  src/app/search/page.tsx
  src/components/Header.tsx
  src/components/information/InformationFrame.tsx
  src/components/main/CardSection/CalculateCard.tsx
  src/components/main/CardSection/NewsCard.tsx
  src/components/main/CardSection/PopularCard.tsx
  src/components/main/FilterSection/FilterSection.tsx
  src/components/main/FilterSection/RadioButton.tsx
  src/components/policyDetail/business/BusinessPay.tsx
  src/components/policyDetail/policy/PolicyReform.tsx
Labels: ✅완료, 👀리뷰, 태강

#29 [Chore] 내용 더보기 페이지 라우팅 수정, map 임시 라우팅 삭제
  src/app/map/page.tsx
  src/app/search-list/page.tsx
  src/components/commonSearch/SearchCard.tsx
Labels: ✅완료, 👀리뷰, 태강

#30 [Feat] 상세페이지 구현
  public/images/BomoLogo.png
  public/images/bus.png
  public/images/calender.png
  public/images/cctv.png
  public/images/clock.png
  public/images/isFree.png
  public/images/kindergarten.png
  public/images/noFee.png
  public/images/playground.png
  public/images/telephone.png
  src/app/about-us/page.tsx
  src/app/detail/page.tsx
  src/components/detail/ContentCard.tsx
  src/components/detail/DetailFrame.tsx
  src/components/detail/KakaoMap.tsx
  src/components/main/FilterSection/FilterSection.tsx
Labels: 👨🏻‍💻작업중, 👀리뷰, 태강

#33 [Feat] React query 구현
  package-lock.json
  package.json
  public/dummy/filterSearchDummy.json
  public/dummy/mainSearchDummy.json
  public/dummy/mapSearchDummy.json
  public/dummy/popularCardDummy.json
  src/app/ReactQueryProvider.tsx
  src/app/layout.tsx
  src/components/commonSearch/DetailSearchFrame.tsx
  src/components/commonSearch/SearchCard.tsx
  src/components/filterSearch/FilterSearchFrame.tsx
  src/components/main/CardSection/PopularCard.tsx
  src/components/mainSearch/MainSearchFrame.tsx
  src/components/mapSearch/MapSearchFrame.tsx
Labels: 👨🏻‍💻작업중, 👀리뷰, 가현

#36 [Feat] api 구현
  package-lock.json
  package.json
  src/app/NextProvider.tsx
  src/app/layout.tsx
  src/components/commonSearch/SearchCard.tsx
  src/components/main/CardSection/PopularCard.tsx
  src/components/main/FilterSection/FilterSection.tsx
  src/components/main/FilterSection/RadioBox.tsx
  src/components/main/FilterSection/RadioButton.tsx
  src/components/main/SearchSection/SearchSection.tsx
  src/components/main/map/MapFrame.tsx
  src/components/mainSearch/MainSearchFrame.tsx
  src/components/mapSearch/MapSearchFrame.tsx
  src/state/index.ts
Labels: 👨🏻‍💻작업중, 태강, 가현

#37 [feat] 인기 복지 클릭 시 상세 페이지 이동 및 결과 없을 시 ui 구현
  src/components/commonSearch/SearchCard.tsx
  src/components/main/CardSection/PopularCard.tsx
  src/components/main/SearchSection/SearchSection.tsx
  src/components/mainSearch/MainSearchFrame.tsx
  src/components/mapSearch/MapSearchFrame.tsx
Labels: 👨🏻‍💻작업중, 👀리뷰, 가현

#38 [Feat] filter search api 구현
  src/components/commonSearch/DetailSearchFrame.tsx
  src/components/commonSearch/SearchCard.tsx
  src/components/filterSearch/FilterSearchFrame.tsx
  src/components/main/FilterSection/FilterSection.tsx
Labels: ✅완료, 👀리뷰, 가현

#39 [Feat] 상세페이지 개요 및 리뷰 탭 구현
  src/app/(header)/detail/[id]/page.tsx
  src/components/detail/DetailFrame.tsx
  src/components/main/CardSection/PopularCard.tsx
  src/components/my/MypageFrame.tsx
Labels: ✅완료, 👀리뷰, 태강

#41 [Feat] pagination 구현
  src/components/commonSearch/DetailSearchFrame.tsx
  src/components/filterSearch/FilterSearchFrame.tsx
  src/components/main/FilterSection/RadioBox.tsx
  src/components/mainSearch/MainSearchFrame.tsx
Labels: ✅완료, 👀리뷰, 태강

#42 [Feat] 소셜 로그인, 카드 캐러셀 구현
  package-lock.json
  package.json
  public/images/news/1.png
  public/images/news/2.jpeg
  public/images/news/3.jpeg
  src/components/login/LoginFrame.tsx
  src/components/login/Oauth.ts
  src/components/main/CardSection/NewsCard.tsx
Labels: 👨🏻‍💻작업중, 👀리뷰, 태강

#43 [Feat] 상세 페이지 api구현
  src/app/(header)/care/[id]/page.tsx
  src/app/(header)/center/[id]/page.tsx
  src/components/commonSearch/DetailSearchFrame.tsx
  src/components/commonSearch/SearchCard.tsx
  src/components/detail/ContentCard.tsx
  src/components/detail/DetailFrame.tsx
  src/components/main/CardSection/PopularCard.tsx
  src/components/mapSearch/MapSearchFrame.tsx
  src/components/searchList/FilterSearchFrame.tsx
  src/components/searchList/MainSearchList.tsx
  src/components/searchList/MapSearchList.tsx
Labels: 👨🏻‍💻작업중, 👥논의필요, 👀리뷰, 가현

#44 [Feat] 카카오 로그인/로그아웃 구현
  package-lock.json
  package.json
  src/app/oauth/kakao/page.tsx
  src/components/Header.tsx
  src/components/login/Oauth.ts
  src/components/my/MypageFrame.tsx
  src/state/index.ts
Labels: ✅완료, 👀리뷰, 태강

#45 [FIX] localStorage -> Recoil 변경 및 로그인 실행 순서 제어 수정
  src/app/oauth/kakao/page.tsx
  src/components/Header.tsx
  src/components/detail/DetailFrame.tsx
  src/components/my/MypageFrame.tsx
  src/state/index.ts
Labels: 🐞버그, ✅완료, 👀리뷰, 태강

#46 [Refactor] kakao map url 수정
  src/components/detail/KakaoMap.tsx
  src/components/login/LoginFrame.tsx
  src/components/main/map/MapFrame.tsx
Labels: 👥논의필요, 가현

#51 [FIX] ssr hydration 에러 해결
  src/components/Header.tsx
Labels: 🐞버그, ✅완료, 태강

#52 [Fix] 카카오맵 에러 수정
  src/components/detail/DetailFrame.tsx
Labels: 🐞버그, 👥논의필요, 👀리뷰

#53 [FIX] 카카오맵 에러 해결
  src/app/layout.tsx
  src/components/Header.tsx
  src/components/detail/ContentCard.tsx
  src/components/detail/DetailFrame.tsx
  src/components/detail/KakaoMap.tsx
  src/state/index.ts
Labels: 🐞버그, ✅완료, 👀리뷰, 태강

#54 [Feat] 게시물 스크랩 구현
  src/app/(header)/about-us/page.tsx
  src/components/detail/DetailFrame.tsx
  src/components/detail/KakaoMap.tsx
Labels: ✅완료, 👀리뷰, 태강

#55 [Feat] 마이페이지 좋아요, 리뷰 조회 구현
  src/components/my/MypageFrame.tsx
  src/components/my/MypageReview.tsx
Labels: ✅완료, 👀리뷰, 가현

#57 [Chore] 링크 이동 구현
  src/app/(header)/error/page.tsx
  src/components/detail/DetailFrame.tsx
  src/components/main/FilterSection/FilterSection.tsx
  src/components/my/MypageFrame.tsx
  src/components/my/MypageReview.tsx
Labels: ✅완료, 👀리뷰, 가현

#58 [Feat] 리뷰 CRUD 구현
  src/components/detail/DetailFrame.tsx
  src/components/detail/Review.tsx
  src/components/searchList/FilterSearchFrame.tsx
Labels: ✅완료, 👀리뷰, 태강

#59 [Refactor] css 수정 및 recoil state 수정
  src/app/layout.tsx
  src/components/my/MypageFrame.tsx
  src/components/my/MypageReview.tsx
Labels: ✅완료, 👀리뷰, 가현

#60 [Chore] 반응형 스타일 수정 및 alert 구현
  src/components/Logo.tsx
  src/components/commonSearch/SearchCard.tsx
  src/components/detail/ContentCard.tsx
  src/components/detail/DetailFrame.tsx
  src/components/detail/KakaoMap.tsx
  src/components/detail/Review.tsx
  src/components/main/CardSection/NewsCard.tsx
  src/components/main/FilterSection/FilterSection.tsx
  src/components/main/FilterSection/RadioBox.tsx
  src/components/my/MypageFrame.tsx
  src/components/my/MypageReview.tsx
Labels: ✅완료, 👀리뷰, 태강

#61 [Refactor] 에러 처리
  src/app/(header)/error/page.tsx
  src/components/detail/DetailFrame.tsx
  src/components/detail/Review.tsx
  src/components/my/MypageReview.tsx
  src/components/searchList/FilterSearchFrame.tsx
  src/components/searchList/MainSearchList.tsx
  src/components/searchList/MapSearchList.tsx
Labels: ✅완료, 👀리뷰, 가현

#62 [Style] 복지 -> 보육 이름 변경
  package-lock.json
  package.json
  public/dummy/filterSearchDummy.json
  public/dummy/mainSearchDummy.json
  public/dummy/mapSearchDummy.json
  public/dummy/popularCardDummy.json
  src/app/(header)/about-us/page.tsx
  src/components/Header.tsx
  src/components/commonSearch/DetailSearchFrame.tsx
  src/components/commonSearch/SearchCard.tsx
  src/components/information/InformationFrame.tsx
  src/components/main/CardSection/PopularCard.tsx
  src/components/main/map/MapFrame.tsx
  src/components/mainSearch/MainSearchFrame.tsx
  src/components/mapSearch/MapSearchFrame.tsx
Labels: ✅완료, 가현

#63 [Feat] Skeleton 구현 및 Type 에러 추가, 에러 체크
  src/app/layout.tsx
  src/components/commonSearch/DetailSearchFrame.tsx
  src/components/commonSearch/SearchCard.tsx
  src/components/commonSearch/SearchSkeleton.tsx
  src/components/detail/DetailFrame.tsx
  src/components/detail/DetailSkeleton.tsx
  src/components/detail/KakaoMap.tsx
  src/components/detail/Review.tsx
  src/components/login/LoginFrame.tsx
  src/components/main/CardSection/NewsCard.tsx
  src/components/main/CardSection/PopularCard.tsx
  src/components/main/SearchSection/SearchSection.tsx
  src/components/mainSearch/MainSearchFrame.tsx
  src/components/mapSearch/MapSearchFrame.tsx
  src/components/mapSearch/MapSearchSkeleton.tsx
  src/components/my/MypageFrame.tsx
  src/components/my/MypageReview.tsx
  src/components/my/MypageSkeleton.tsx
  src/components/searchList/FilterSearchFrame.tsx
  src/components/searchList/FilterSearchSkeleton.tsx
  src/components/searchList/MainSearchList.tsx
  src/components/searchList/MapSearchList.tsx
  src/components/searchList/SearchListSkeleton.tsx
Labels: ✅완료, 👀리뷰, 태강

#65 hotfix: 카카오맵 에러 수정
  src/components/detail/DetailFrame.tsx
  src/components/detail/KakaoMap.tsx
Labels: 🐞버그, 👨🏻‍💻작업중, 👀리뷰, 태강

#67 [FIX] 소셜로그인 시 카카오맵 API InJection
  src/app/NextProvider.tsx
  src/app/layout.tsx
  src/components/detail/DetailFrame.tsx
  src/components/detail/KakaoMap.tsx
  src/components/searchList/MainSearchList.tsx
  src/components/searchList/MapSearchList.tsx
Labels: 🐞버그, ✅완료, 👀리뷰, 태강

#68 [Style] 정책명 수정
  src/components/information/InformationFrame.tsx
  src/components/main/FilterSection/FilterSection.tsx
  src/components/policyDetail/business/BusinessCare.tsx
  src/components/policyDetail/business/BusinessPay.tsx
  src/components/policyDetail/childcare/CareWaitingAdmission.tsx
  src/components/policyDetail/policy/PolicyExpansion.tsx
  src/components/policyDetail/policy/PolicyHistory.tsx
  src/components/policyDetail/policy/PolicyStatus.tsx
Labels: ✅완료, 가현
